config/routes.rb
Rails.application.routes.draw do

  # 会員用
  # URL /members/sign_in ...
  # 会員のパスワード編集は削除
  devise_for :members, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }
  devise_scope :member do
    post "members/guest_sign_in", to: "public/sessions#guest_sign_in"
  end

  scope module: :public do
    root "homes#top"
    get "homes/about"
    resources :members, only: [:index, :show, :edit, :update] do
      resource :relationships, only: [:create, :destroy]
      get "followings" => "relationships#followings"
      get "followers"  => "relationships#followers"
      member do
        get :likes
      end
    end
    get "members/:id/confirm" => "members#confirm", as: "confirm"
    patch "members/:id/withdraw" => "members#withdraw", as: "withdraw"
    resources :posts, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
      resource  :likes,    only: [:create, :destroy]
      member do
        get :likes
      end
      resources :comments, only: [:create, :destroy]
    end
    get "searches/search"
    resources :messages,      only: [:create, :destroy]
    resources :rooms,         only: [:create, :index, :show]
    resources :notifications, only: :index
    delete "destroy_all" => "notifications#destroy_all", as: "destroy_all"
  end

  # 管理者用
  # URL /admin/sign_in ...
  # 管理者の登録とパスワードの編集は削除
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
    resources :posts, only: [:index, :show, :destroy] do
      resources :comments, only: :destroy
    end
    resources :members, only: [:index, :show, :edit, :update]
    get "searches/search"
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/member.rb
class Member < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :relationships, foreign_key: :follower_id, dependent: :destroy
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: :followed_id, dependent: :destroy
  has_many :followings, through: :relationships, source: :followed
  has_many :followers, through: :reverse_of_relationships, source: :follower
  has_many :comments, dependent: :destroy
  has_many :entries, dependent: :destroy
  has_many :active_notifications, class_name: "Notification", foreign_key: "visitor_id", dependent: :destroy
  has_many :passive_notifications, class_name: "Notification", foreign_key: "visited_id", dependent: :destroy

  validates :name, length: { minimum: 2, maximum: 20 }, presence: true
  has_one_attached :profile_image

  def get_profile_image
    (profile_image.attached?) ? profile_image : "no-image.PNG"
  end

  def self.guest
    find_or_create_by!(email: "guest@example.com") do |member|
      member.password = SecureRandom.urlsafe_base64
      member.password_confirmation = member.password
      member.name = "ゲスト"
    end
  end

  def follow(member)
    relationships.create(followed_id: member.id)
  end

  def unfollow(member)
    relationships.find_by(followed_id: member.id).destroy
  end

  def following?(member)
    followings.include?(member)
  end

  def self.looks(search, word)
    @member = Member.where("name LIKE?","%#{word}%")  #部分一致のみ
  end

  def create_notification_follow!(current_member)
    temp = Notification.where(["visitor_id = ? and visited_id = ? and action = ? ", current_member.id, id, "follow"])
    if temp.blank?
      notification = current_member.active_notifications.new(
        visited_id: id,
        action: "follow"
      )
      notification.save if notification.valid?
    end
  end
end

app/controllers/admin/members_controller.rb
class Admin::MembersController < ApplicationController
  before_action :authenticate_admin!
  def index
    @members = Member.all.page(params[:page]).per(15)
  end

  def show
    @member = Member.find(params[:id])
    @posts = @member.posts.page(params[:page]).per(8)
    @today = Date.today #今日の日付を取得
    @now = Time.now     #現在時刻を取得
  end

  def edit
    @member = Member.find(params[:id])
  end

  def update
    member = Member.find(params[:id])
    member.update(member_params)
    flash[:notice] = "会員情報を更新しました。"
    redirect_to admin_members_path
  end

  private

  def member_params
    params.require(:member).permit(:is_deleted)
  end
end

app/helpers/admin/members_helper.rb
module Admin::MembersHelper
end

app/views/admin/members/_index.html.erb
<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col"></th>
      <th scope="col">ニックネーム</th>
      <th scope="col">自己紹介</th>
      <th scope="col">退会ステータス</th>
      <th scope="col"></th>
    </tr>
  </thead>
  <tbody>
    <% @members.each do |member| %>
    <tr>
      <td class="profile_image">
        <%= link_to admin_member_path(member.id) do %>
          <%= image_tag member.get_profile_image %>
        <% end %>
      </td>
      <td><%= member.name %></td>
      <td><%= truncate(member.introduction, length: 30) %></td>  <!--15字まで表示-->
      <td>
        <% if member.is_deleted == false %>
          <strong class="text-success"><%= "有効" %></strong>
        <% else %>
          <strong class= "text-secondary"><%= "退会" %></strong>
        <% end %>
      </td>
      <td>
        <%= link_to edit_admin_member_path(member.id), class: "btn btn-outline-secondary" do %>
          <i class="fas fa-user-edit"></i>
        <% end %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/members/edit.html.erb
<div class="container">
  <div class="row">
    <div class="mx-auto col-10">
      <h2>会員を編集</h2>
    </div>
    <div class="mx-auto col-8">
      <%= form_with model: @member, url: admin_member_path, method: :patch, local: true do |f| %>
        <table class="table">
          <tr>
            <th></th>
            <th><%= image_tag @member.get_profile_image %></th>
            <th></th>
          </tr>
          <tr>
            <th>ニックネーム</th>
            <th><%= @member.name %></th>
            <th></th>
          </tr>
          <tr>
            <th>自己紹介</th>
            <th><%= @member.introduction %></th>
            <th></th>
          </tr>
          <tr>
            <th>退会ステータス</th>
            <th>
              <%= f.radio_button :is_deleted, :false %>
              <%= f.label :is_deleted, "有効",{value: :false, style: "display: inline-block;"} %>
            </th>
            <th>
              <%= f.radio_button :is_deleted, :true %>
              <%= f.label :is_deleted, "退会",{value: :true, style: "display: inline-block;"} %>
            </th>
          </tr>
          <tr>
            <th></th>
            <th><%= f.submit "編集する", class: "btn btn-outline-secondary" %></th>
            <th></th>
          </tr>
        </table>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/members/index.html.erb
<div class="container">
  <div class="row">
    <div class="mx-auto col-10">
      <h2>会員一覧</h2>
      <%= render "index", members: @member %>
    </div>
  </div>
  <%= paginate @members %>
</div>

app/views/admin/members/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-4">
      <table class="table">
        <h2 style="text-align: center;"><%= @member.name %>のプロフィール</h2>
        <tr>
          <th><%= image_tag @member.get_profile_image %></th>
          <th></th>
        </tr>
        <tr>
          <th>投稿</th>
          <th><%= @member.posts.count %></th>
        </tr>
        <tr>
          <th>ニックネーム</th>
          <th colspan="2"><%= @member.name %></th>
        </tr>
        <tr>
          <th>自己紹介</th>
          <th colspan="2"><%= @member.introduction %></th>
        </tr>
      </table>
      <%= link_to edit_admin_member_path(@member.id), class: "btn btn-outline-secondary btn-block" do %>
        <i class="fas fa-user-edit"></i>会員情報を編集
      <% end %>
    </div>
    <div class="col-8">
      <div class="card-deck">
        <% @posts.each do |post| %>
          <div class="col-md-6">
            <div class="card mb-4 shadow-sm">
              <div class="card-header">
                <%= image_tag post.member.get_profile_image %>
              </div>
              <% if post.post_images.present? %>
                <div class="card-img-top slicker_non_auto">
                  <% post.post_images.each do |image| %>
                    <%= link_to admin_post_path(post.id) do %>
                      <%= image_tag(image, width: "200px") %>
                    <% end %>
                  <% end %>
                </div>
                <p class="text-right mr-3">image:<%= post.post_images.count %></p>
              <% end %>
              <div class="card-body">
                <span>
                  <%= render "public/comments/count", post: post %>
                </span><br><br>
                <%= link_to admin_post_path(post.id) do %>
                  <h5 class="card-title"><%= post.title %></h4>
                <% end %>
                <p class="card-text"><%= post.body.truncate(50) %></p>  <!--50字まで表示-->
              </div>
              <div class="card-footer">
                <%= render 'public/posts/time', post: post %>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
  <%= paginate @posts %>
</div>