config/routes.rb
Rails.application.routes.draw do

  # 会員用
  # URL /members/sign_in ...
  # 会員のパスワード編集は削除
  devise_for :members, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }
  devise_scope :member do
    post "members/guest_sign_in", to: "public/sessions#guest_sign_in"
  end

  scope module: :public do
    root "homes#top"
    get "homes/about"
    resources :members, only: [:index, :show, :edit, :update] do
      resource :relationships, only: [:create, :destroy]
      get "followings" => "relationships#followings"
      get "followers"  => "relationships#followers"
      member do
        get :likes
      end
    end
    get "members/:id/confirm" => "members#confirm", as: "confirm"
    patch "members/:id/withdraw" => "members#withdraw", as: "withdraw"
    resources :posts, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
      resource  :likes,    only: [:create, :destroy]
      member do
        get :likes
      end
      resources :comments, only: [:create, :destroy]
    end
    get "searches/search"
    resources :messages,      only: [:create, :destroy]
    resources :rooms,         only: [:create, :index, :show]
    resources :notifications, only: :index
    delete "destroy_all" => "notifications#destroy_all", as: "destroy_all"
  end

  # 管理者用
  # URL /admin/sign_in ...
  # 管理者の登録とパスワードの編集は削除
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
    resources :posts, only: [:index, :show, :destroy] do
      resources :comments, only: :destroy
    end
    resources :members, only: [:index, :show, :edit, :update]
    get "searches/search"
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord

  belongs_to :member
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :notifications, dependent: :destroy

  validates :title, length: { minimum: 2, maximum: 30 }, presence: true
  has_many_attached :post_images

  scope :latest, -> {order(created_at: :desc)}
  scope :old, -> {order(created_at: :asc)}
  # 過去1週間のいいね数順に表示される
  to = Time.current.at_end_of_day
  from = (to - 6.day).at_beginning_of_day
  scope :week_likes, -> {includes(:member).sort {|a,b| b.likes.where(created_at: from...to).size <=> a.likes.where(created_at: from...to).size}}

  def liked_by?(member)
    likes.exists?(member_id: member.id)
  end

  def self.looks(search, word)
    @post = Post.where("title LIKE?","%#{word}%")  #部分一致のみ
  end

  def create_notification_like!(current_member)
    notification = current_member.active_notifications.new(
      post_id: id,
      visited_id: member_id,
      action: "like"
    )
    notification.save if notification.valid?
  end

  def create_notification_comment!(current_member, comment_id)
    # 自分以外にコメントしている人をすべて取得し、全員に通知を送る
    # distinctメソッドは重複レコードを1つにまとめるためのメソッド
    temp_ids = Comment.select(:member_id).where(post_id: id).where.not(member_id: current_member.id).distinct
    temp_ids.each do |temp_id|
      save_notification_comment!(current_member, comment_id, temp_id["member_id"])
    end
    # まだ誰もコメントしていない場合は、投稿者に通知を送る
    save_notification_comment!(current_member, comment_id, member_id) if temp_ids.blank?
  end

  def save_notification_comment!(current_member, comment_id, visited_id)
    # コメントは複数回することが考えられるため、１つの投稿に複数回通知する
    notification = current_member.active_notifications.new(
      post_id: id,
      comment_id: comment_id,
      visited_id: visited_id,
      action: "comment"
    )
    # 自分の投稿に対するコメントの場合は、通知済みとする
    if notification.visitor_id == notification.visited_id
      notification.checked = true
    end
    notification.save if notification.valid?
  end
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController
  before_action :authenticate_admin!
  def index
    @today = Date.today  # 今日の日付を取得
    @now = Time.now      # 現在時刻を取得
    if params[:old]
      @posts = Post.old.page(params[:page]).per(15)                          # 古い順
    elsif params[:week_likes]
      posts = Post.week_likes
      @posts =  Kaminari.paginate_array(posts).page(params[:page]).per(15)   # 過去1週間のいいね数順に表示される
    else
      @posts = Post.latest.page(params[:page]).per(15)                       # 新着順
    end
  end

  def show
    @today = Date.today #今日の日付を取得
    @now = Time.now     #現在時刻を取得
    @post = Post.find(params[:id])
    @comment = Comment.new
  end

  def destroy
    post = Post.find(params[:id])
    post.destroy
    redirect_to admin_posts_path
  end
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/views/admin/posts/_comments.html.erb
<% post.comments.each do |comment| %>
  <table class="mx-auto">
    <th class="profile_image">
      <%= link_to admin_member_path(comment.member.id) do %>
        <%= image_tag comment.member.get_profile_image, size: "40x40" %>
      <% end %>
    </th>
    <th width="400">
      <%= comment.comment %>
    </th>
    <th>
      <%= link_to admin_post_comment_path(post, comment), method: :delete, data: { confirm: "本当に消しますか？" } do %>
        <i class="fas fa-trash-alt"></i>
      <% end %>
    </th>
  </table>
<% end %>

app/views/admin/posts/_index.html.erb
<div class="card mb-4 shadow-sm">
  <div class="card-header">
    <%= link_to admin_member_path(post.member.id) do %>
      <%= image_tag post.member.get_profile_image, size: "30x30" %>
    <% end %>
  </div>
  <% if post.post_images.present? %>
    <div class="card-img-top slicker_non_auto">
      <% post.post_images.each do |image| %>
        <%= link_to admin_post_path(post.id) do %>
          <%= image_tag(image, width: "200px") %>
        <% end %>
      <% end %>
    </div>
    <p class="text-right mr-3">image:<%= post.post_images.count %></p>
  <% end %>
  <div class="card-body">
    <span>
      <%= render "public/comments/count", post: post %>
    </span><br><br>
    <%= link_to admin_post_path(post.id) do %>
      <h5 class="card-title"><%= post.title %></h4>
    <% end %>
    <p class="card-text"><%= post.body.truncate(50) %></p>  <!--50字まで表示-->
  </div>
  <div class="card-footer">
    <%= render 'public/posts/time', post: post %>
  </div>
</div>

app/views/admin/posts/index.html.erb
<div class="container">
  <div class="row">
    <div class="mx-auto col-10">
      <h2>投稿一覧</h2>
      <p>
        <%= link_to "新着順", admin_posts_path(latest: "true") %>
        |<%= link_to "古い順", admin_posts_path(old: "true") %>
        |<%= link_to "人気が多い順(週間)", admin_posts_path(week_likes: "true") %>
      </p>
    </div>
  </div>
  <div class="card-deck">
    <% @posts.each do |post| %>
      <div class="col-md-4">
        <%= render "admin/posts/index", post: post %>
      </div>
    <% end %>
  </div>
  <%= paginate @posts %>
</div>

app/views/admin/posts/show.html.erb
<div class="container">
  <div class="row mb-3">
    <div class="mx-auto col-10">
      <h2>投稿詳細</h2>
    </div>
  </div>
  <div class="row mb-3">
    <div class="mx-auto col-8">
      <div class="card mb-4 shadow-sm">
        <div class="card-header">
          <div class="float-left">
            <%= link_to admin_member_path(@post.member.id) do %>
              <%= image_tag @post.member.get_profile_image, size: "40x40" %>
            <% end %>
          </div>
          <div class="float-right">
            <%= link_to admin_post_path, method: :delete, data: { confirm: "本当に消しますか？" }, class: "btn btn-outline-danger" do %>
              <i class="fas fa-trash"></i>
            <% end %>
          </div>
        </div>
        <% if @post.post_images.present? %>
          <div class="card-img-top slicker_non_auto">
            <% @post.post_images.each do |image| %>
              <%= link_to image_tag(image, width: "400px"), url_for(image) %>
            <% end %>
          </div>
          <p class="text-right mr-3">image:<%= @post.post_images.count %></p>
        <% end %>
        <div class="card-body">
          <span>
            <%= render "public/comments/count", post: @post %>
          </span><br><br>
          <h3 class="card-title"><%= @post.title %></h3>
          <p class="card-text" style="font-size: 20px;"><%= @post.body %></p>
        </div>
        <div><%= render "comments", post: @post, comment: @comment %></div>
        <div class="card-footer"><%= render "public/posts/time", post: @post %></div>
      </div>
    </div>
  </div>
</div>