config/routes.rb
Rails.application.routes.draw do

  # 会員用
  # URL /members/sign_in ...
  # 会員のパスワード編集は削除
  devise_for :members, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }
  devise_scope :member do
    post "members/guest_sign_in", to: "public/sessions#guest_sign_in"
  end

  scope module: :public do
    root "homes#top"
    get "homes/about"
    resources :members, only: [:index, :show, :edit, :update] do
      resource :relationships, only: [:create, :destroy]
      get "followings" => "relationships#followings"
      get "followers"  => "relationships#followers"
      member do
        get :likes
      end
    end
    get "members/:id/confirm" => "members#confirm", as: "confirm"
    patch "members/:id/withdraw" => "members#withdraw", as: "withdraw"
    resources :posts, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
      resource  :likes,    only: [:create, :destroy]
      member do
        get :likes
      end
      resources :comments, only: [:create, :destroy]
    end
    get "searches/search"
    resources :messages,      only: [:create, :destroy]
    resources :rooms,         only: [:create, :index, :show]
    resources :notifications, only: :index
    delete "destroy_all" => "notifications#destroy_all", as: "destroy_all"
  end

  # 管理者用
  # URL /admin/sign_in ...
  # 管理者の登録とパスワードの編集は削除
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
    resources :posts, only: [:index, :show, :destroy] do
      resources :comments, only: :destroy
    end
    resources :members, only: [:index, :show, :edit, :update]
    get "searches/search"
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.erb
<footer>
  <div>Copyright © Fumimaru. All Rights Reserved.</div>
</footer>

app/views/layouts/_header.html.erb
<header class="shadow-sm sticky-top">
  <nav class="navbar navbar-expand-lg navbar-light">
    <div class="container">
      <%= link_to root_path do %>
        <%= image_tag 'Dogs-logo.PNG', style: "width: 70px; margin-right: 10px;" %>
      <% end %>
      <%= flash[:notice] %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
          <!--会員ログイン時-->
          <% if member_signed_in? %>
            <li class="nav-item">
              <%= link_to members_path, class: 'nav-link text-dark' do %>
                <%= image_tag 'Dogs-logo2.PNG', style: "width: 20px;" %>会員一覧
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to new_post_path, class: 'nav-link text-dark' do %>
                <%= image_tag 'Dogs-logo2.PNG', style: "width: 20px;" %>投稿する
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to posts_path, class: 'nav-link text-dark' do %>
                <%= image_tag 'Dogs-logo2.PNG', style: "width: 20px;" %>みんなの投稿
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to rooms_path, class: 'nav-link text-dark' do %>
                <%= image_tag 'Dogs-logo2.PNG', style: "width: 20px;" %>チャット
              <% end %>
            </li>

            <li class="nav-item">
              <%= link_to notifications_path, class: 'nav-link text-dark' do %>
                <% if unchecked_notifications.any? %>
                  <i class="fa fa-circle" style="color: red; width: 10px; vertical-align: top;"></i>
                <% end %>
                <%= image_tag 'Dogs-logo2.PNG', style: "width: 20px;" %>通知
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to destroy_member_session_path, method: :delete, class: 'nav-link text-dark' do %>
                <%= image_tag 'Dogs-logo2.PNG', style: "width: 20px;" %>ログアウト
              <% end %>
            </li>
            <li class="nav-item profile_image">
              <%= link_to member_path(current_member), class: 'nav-link text-dark' do %>
                <%= image_tag current_member.get_profile_image %>
              <% end %>
            </li>
          <% else %>
            <!--会員ログアウト時-->
            <li class="nav-item">
              <%= link_to homes_about_path, class: 'nav-link text-dark' do %>
                <%= image_tag 'Dogs-logo2.PNG', style: "width: 20px;" %>Dog-love-assemblyって？
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to new_member_registration_path, class: 'nav-link text-dark' do %>
                <%= image_tag 'Dogs-logo2.PNG', style: "width: 20px;" %>新規会員登録
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to new_member_session_path, class: 'nav-link text-dark' do %>
                <%= image_tag 'Dogs-logo2.PNG', style: "width: 20px;" %>会員ログイン
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to members_guest_sign_in_path, class: 'nav-link text-dark', method: :post do %>
                <%= image_tag 'Dogs-logo2.PNG', style: "width: 20px;" %>ゲストログイン
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to admin_session_path, class: 'nav-link text-dark', method: :post do %>
                <%= image_tag 'Dogs-logo2.PNG', style: "width: 20px;" %>管理者ログイン
              <% end %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Dog-love-assembly</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Mochiy+Pop+One&display=swap" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css"/>
    <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick-theme.css"/>
    <script type="text/javascript" src="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js"></script>
  </head>

  <body>
    <!--管理者のログイン状況でヘッダーが分岐-->
    <!--管理者ログイン時-->
    <% if admin_signed_in? %>
      <%= render 'admin/layouts/header' %>
      <!--その他-->
    <% else %>
      <%= render 'layouts/header' %>
    <% end %>
    <main>
      <% if member_signed_in? %>
        <div class="search_form">
          <%= form_with url: searches_search_path, method: :get, local: true do |f| %>
            <%= f.select :range, options_for_select([["会員を探す"], ["投稿を探す"]]) %>
            <%= f.text_field :word %>
            <%= f.submit "検索" %>
          <% end %>
        </div><br>
      <% end %>
      <% if admin_signed_in? %>
        <div class="search_form">
          <%= form_with url: admin_searches_search_path, method: :get, local: true do |f| %>
            <%= f.select :range, options_for_select([["会員を探す"], ["投稿を探す"]]) %>
            <%= f.text_field :word %>
            <%= f.submit "検索" %>
          <% end %>
        </div><br>
      <% end %>
      <%= yield %>
    </main>
    <%= render 'layouts/footer' %>
  </body>
</html>